name: ASDF Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9 Testing
            os: ubuntu-latest
            python-version: 3.9
            toxenv: py39

          - name: Numpy 1.11
            os: ubuntu-latest
            python-version: 3.6.10
            toxenv: py36-numpy11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
