name: ASDF Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9 Testing
            os: ubuntu-latest
            python-version: 3.9
            toxenv: py39

          - name: Astropy Dev
            os: ubuntu-latest
            python-version: 3.8
            toxenv: py38-astropydev

          - name: GWCS Dev
            os: ubuntu-latest
            python-version: 3.8
            toxenv: py38-gwcsdev

          - name: Numpy Dev
            os: ubuntu-latest
            python-version: 3.8
            toxenv: py38-numpydev

          - name: Pre-Release Dependencies
            os: ubuntu-latest
            python-version: 3.8
            toxenv: prerelease

          - name: Test Against Installed Packaged
            os: ubuntu-latest
            python-version: 3.8
            toxenv: packaged

          - name: Warnings Treated as Exceptions
            os: ubuntu-latest
            python-version: 3.8
            toxenv: warnings
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
