name: ASDF Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Actual jobs removed to isolate big endian testing
        run: echo "No operation"
