name: ASDF Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9 Testing
            os: ubuntu-latest
            python-version: 3.9
            toxenv: py39

          - name: Code Style Checks
            os: ubuntu-latest
            python-version: 3.8
            toxenv: style

    steps:
      - name: Install System Packages
        if: ${{ contains(matrix.toxenv,'docbuild') }}
        run: |
          sudo apt-get install graphviz texlive-latex-extra dvipng
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          # git submodule update --init --recursive
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}

  big_endian_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: uraimo/run-on-arch-action@2.0.5
      with:
        arch: s390x
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
          pip install tox
    - name: Run tox
      run: |
        tox -e s390x
