name: ASDF Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        flake8 asdf --count --show-source --statistics

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[tests]
    - name: Test with pytest
      run: |
        pytest

  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9
            os: ubuntu-latest
            python-version: 3.9
            toxenv: py39

          - name: Python 3.8
            os: ubuntu-latest
            python-version: 3.8
            toxenv: py38

          - name: Python 3.7
            os: ubuntu-latest
            python-version: 3.7.9
            toxenv: py37

          - name: Python 3.6
            os: ubuntu-latest
            python-version: 3.6.10
            toxenv: py36
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
